export const SUCCESSFUL_REGISTER = 'REGISTER_SUCCESSFUL';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const OBTAIN_USER = 'OBTAIN_USER';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const READ_USERLIST = 'READ_USERLIST';
export const DELETE_USER = 'DELETE_USER';
export const SELECTED_USER = 'SELECTED_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const RESET_FIELDS = 'RESET_FIELDS';
